### ISSUE TITLE
withTransactionOnCommandBus(true) / Uncaught PDOException: There is no active transaction

### ISSUE THREAD

**Issue by aheissenberger** [ecotoneframework/ecotone#17]
**Ecotone version(s) affected**: 1.22.11
Module: ecotoneframework/dbal 1.22.11

**Description**  
Using this configuration `withTransactionOnCommandBus(true)` will crash with a Fatal error when no tables exist in the database:

```php
DbalConfiguration::createWithDefaults()
            ->withTransactionOnCommandBus(true)
            ->withDocumentStore(initializeDatabaseTable: true),
```

The problem is based on the fact that after in line 52 `START TRANSACTION` this ` $result = $methodInvocation->proceed();` statement will issue multiple `CREATE TABLE` (see SQL log in context section) which do [auto commit](https://dev.mysql.com/doc/refman/8.0/en/implicit-commit.html) which will make the commit command in line 58  fail.

https://github.com/ecotoneframework/dbal/blob/d08dfba59a66cd1f21e96dcebd251ec805e1dee6/src/Dbal/DbalTransaction/DbalTransactionInterceptor.php#L51-L66

**How to reproduce**  

**Possible Solution**  

A) do not try a rollback and throwing an exception if the Exception is a failed commit
B) remember creating new tables and skip the commit
c) check `SELECT @@autocommit` which should be `0` inside an not committed transaction.

**Context**  

**Error Msg**
```
Fatal error: Uncaught PDOException: There is no active transaction in /workspace/App/vendor/doctrine/dbal/src/Driver/PDO/Connection.php:118
Stack trace:
#0 /workspace/App/vendor/doctrine/dbal/src/Driver/PDO/Connection.php(118): PDO->commit()
#1 /workspace/App/vendor/doctrine/dbal/src/Connection.php(1348): Doctrine\DBAL\Driver\PDO\Connection->commit()
#2 /workspace/App/vendor/ecotone/dbal/src/Dbal/DbalTransaction/DbalTransactionInterceptor.php(58): Doctrine\DBAL\Connection->commit()
```

**Database Calls**
between line 52 and line 58 ending with the fatal error

```sql
2022-06-11 01:26:27.955032	[mariadb] @  [172.18.0.2]	23	1	Connect	mariadb@172.18.0.2 on mariadb using TCP/IP
2022-06-11 01:26:27.956247	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	START TRANSACTION
2022-06-11 01:27:26.252657	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'
2022-06-11 01:27:26.254301	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	CREATE TABLE `event_streams` (↵    `no` BIGINT(20) NOT NULL AUTO_INCREMENT,↵    `real_stream_name` VARCHAR(150) NOT NULL,↵    `stream_name` CHAR(41) NOT NULL,↵    `metadata` LONGTEXT NOT NULL,↵    `category` VARCHAR(150),↵    CHECK (`metadata` IS NOT NULL OR JSON_VALID(`metadata`)),↵    PRIMARY KEY (`no`),↵    UNIQUE KEY `ix_rsn` (`real_stream_name`),↵    KEY `ix_cat` (`category`)↵) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
2022-06-11 01:27:26.258758	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'
2022-06-11 01:27:26.259131	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	CREATE TABLE `projections` (↵  `no` BIGINT(20) NOT NULL AUTO_INCREMENT,↵  `name` VARCHAR(150) NOT NULL,↵  `position` LONGTEXT,↵  `state` LONGTEXT,↵  `status` VARCHAR(28) NOT NULL,↵  `locked_until` CHAR(26),↵  CHECK (`position` IS NULL OR JSON_VALID(`position`)),↵  CHECK (`state` IS NULL OR JSON_VALID(`state`)),↵  PRIMARY KEY (`no`),↵  UNIQUE KEY `ix_name` (`name`)↵) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin
2022-06-11 01:27:26.265775	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	SELECT COUNT(1) FROM `event_streams`↵WHERE real_stream_name = 'Ecotone\\App\\Wallet'
2022-06-11 01:27:26.266916	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	INSERT INTO `event_streams` (real_stream_name, stream_name, metadata, category)↵VALUES ('Ecotone\\App\\Wallet', '_178a8da9783a0ac460e695cbe0ee48ca321244eb', '[]', NULL)
2022-06-11 01:27:26.267444	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	CREATE TABLE `_178a8da9783a0ac460e695cbe0ee48ca321244eb` (↵    `no` BIGINT(20) NOT NULL AUTO_INCREMENT,↵    `event_id` CHAR(36) COLLATE utf8mb4_bin NOT NULL,↵    `event_name` VARCHAR(100) COLLATE utf8mb4_bin NOT NULL,↵    `payload` LONGTEXT NOT NULL,↵    `metadata` LONGTEXT NOT NULL,↵    `created_at` DATETIME(6) NOT NULL,↵    `aggregate_version` INT(11) UNSIGNED GENERATED ALWAYS AS (JSON_EXTRACT(metadata, '$._aggregate_version')) STORED,↵    `aggregate_id` CHAR(36) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(metadata, '$._aggregate_id'))) STORED,↵    `aggregate_type` VARCHAR(150) GENERATED ALWAYS AS (JSON_UNQUOTE(JSON_EXTRACT(metadata, '$._aggregate_type'))) STORED,↵    CHECK (`payload` IS NOT NULL AND JSON_VALID(`payload`)),↵    CHECK (`metadata` IS NOT NULL AND JSON_VALID(`metadata`)),↵    PRIMARY KEY (`no`),↵    UNIQUE KEY `ix_event_id` (`event_id`),↵    UNIQUE KEY `ix_unique_event` (`aggregate_type`, `aggregate_id`, `aggregate_version`),↵    KEY `ix_query_aggregate` (`aggregate_type`,`aggregate_id`,`no`)↵) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_bin
2022-06-11 01:27:26.270762	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	INSERT INTO `_178a8da9783a0ac460e695cbe0ee48ca321244eb` (event_id, event_name, payload, metadata, created_at) VALUES ('a38335ba-c928-43c1-8ce2-52afeca0c64b', 'Ecotone\\App\\WalletWasRegistered', '{\"walletId\":1}', '{\"id\":\"a38335ba-c928-43c1-8ce2-52afeca0c64b\",\"timestamp\":1654910839,\"_aggregate_id\":1,\"_aggregate_type\":\"Ecotone\\\\App\\\\Wallet\",\"_aggregate_version\":1}', '2022-06-11T01:27:19.000000')
2022-06-11 01:28:09.688576	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	SHOW FULL TABLES WHERE Table_type = 'BASE TABLE'
2022-06-11 01:28:21.437566	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	CREATE TABLE enqueue (id CHAR(36) NOT NULL COMMENT '(DC2Type:guid)', published_at BIGINT NOT NULL, body LONGTEXT DEFAULT NULL, headers LONGTEXT DEFAULT NULL, properties LONGTEXT DEFAULT NULL, redelivered TINYINT(1) DEFAULT NULL, queue VARCHAR(255) NOT NULL, priority SMALLINT DEFAULT NULL, delayed_until BIGINT DEFAULT NULL, time_to_live BIGINT DEFAULT NULL, delivery_id CHAR(36) DEFAULT NULL COMMENT '(DC2Type:guid)', redeliver_after BIGINT DEFAULT NULL, INDEX IDX_CFC35A6862A6DC27E0D4FDE17FFD7F63121369211A065DF8BF396750 (priority, published_at, queue, delivery_id, delayed_until, id), INDEX IDX_CFC35A68AA0BDFF712136921 (redeliver_after, delivery_id), INDEX IDX_CFC35A68E0669C0612136921 (time_to_live, delivery_id), INDEX IDX_CFC35A6812136921 (delivery_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB
2022-06-11 01:28:21.465037	mariadb[mariadb] @  [172.18.0.2]	23	1	Query	INSERT INTO enqueue (id, published_at, body, headers, properties, priority, queue, redelivered, delivery_id, redeliver_after) VALUES ('1cc654ce-0a22-445f-b9c8-19ccca2fe670', 16549109014632, '{\"walletId\":1}', '[]', '{\"id\":\"6bb2176d-4816-42e9-90ff-4462b7068740\",\"timestamp\":1654910890,\"routingSlip\":\"onWalletRegistered.target.async\",\"__TypeId__\":\"Ecotone\\\\App\\\\WalletWasRegistered\",\"contentType\":\"application\\/json\"}', 0, 'asynchronous_projections', 0, NULL, NULL)
```

**Comment by dgafka** [comment]
@aheissenberger work in progress my friend :)

**Comment by dgafka** [comment]
@aheissenberger starting from `1.30.0`, implicit commit is now handled correctly with transaction interceptor :)
